services:
  docs:
    image: squidfunk/mkdocs-material
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    environment:
      - MKDOCS_BUILD_TOOL=uv
    command: serve --dev-addr 0.0.0.0:8000
