site_name: Finks Data Pipeline
site_url: https://Finks-ai.github.io/finks-data-architecture/
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.instant
    - header.autohide
    - content.tooltips
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: orange
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: orange
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  version:
    provider: mike
    default: latest

extra_css:
  - stylesheets/gruvbox.css

plugins:
  - search
  - mike:
      version_selector: true
      css_dir: stylesheets
      javascript_dir: javascripts
      canonical_version: latest

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Architecture:
      - Overview: architecture-overview/index.md
      - Core Components: core-components/index.md
      - Data Lake: data-lake-architecture/index.md
      - Service Architecture: service-architecture/index.md
      - Detailed Flow: detailed-flow/index.md
  - Implementation:
      - Technology Stack: technology-stack/index.md
      - Infrastructure as Code:
          - "overview": "infrastructure-as-code/index.md"
          - "details": "infrastructure-as-code.md"
      - Transformation with dbt: transformation-layer/index.md
      - Roadmaps:
          - "Project Roadmap": "roadmaps/project-roadmap.md"
          - "Aggressive Timeline": "roadmaps/aggressive-timeline.md"
          - "Agentic Sessions":
              - "Overview": "roadmaps/agentic-sessions/index.md"
              - "Week 0: Preparation": "roadmaps/agentic-sessions/week-0-preparation.md"
              - "Week 1: Foundation": "roadmaps/agentic-sessions/week-1-foundation.md"
              - "Week 2: Infrastructure": "roadmaps/agentic-sessions/week-2-infrastructure.md"
              - "Week 3: Orchestration": "roadmaps/agentic-sessions/week-3-orchestration.md"
              - "Week 4: Transformation": "roadmaps/agentic-sessions/week-4-transformation.md"
              - "Week 5: Pipeline": "roadmaps/agentic-sessions/week-5-pipeline.md"
              - "Week 6: Production": "roadmaps/agentic-sessions/week-6-production.md"
              - "Best Practices": "roadmaps/agentic-sessions/best-practices.md"

  - Operations:
      - Security: security-architecture/index.md
      - Cost Optimization: cost-optimization/index.md
      - Monitoring & Observability: monitoring-observability/index.md
  - Reference:
      - Technology Decisions: technology-decisions/index.md
      - Repositories: repositories/index.md
      - Environment Management: environment-management/index.md
