name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Deploy on version tags like v0.2.0, v1.0.0

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Set up uv
        run: pip install uv

      - name: Install dependencies
        run: uv pip install . --system

      - name: Deploy with Mike
        run: |
          # For tagged versions (e.g., v0.2.0)
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#v}"  # Remove 'v' prefix
            uv run mike deploy --push --update-aliases $VERSION latest
          # For main branch commits
          else
            # Get version from pyproject.toml or use dev
            VERSION=$(grep "^version" pyproject.toml | cut -d'"' -f2 || echo "dev")
            uv run mike deploy --push $VERSION
          fi
